# tasks file for supervisor
---
- include: install.yml
  tags:
    - configuration
    - supervisor
    - supervisor-install

- include: configure.yml
  tags:
    - configuration
    - supervisor
    - supervisor-configure

- include: programs.yml
  tags:
    - configuration
    - supervisor
    - supervisor-programs

- include: groups.yml
  tags:
    - configuration
    - supervisor
    - supervisor-groups

- name: start and enable service
  shell: service supervisor restart
  when: supervisor_state == 'start'
  tags:
    - configuration
    - supervisor
    - supervisor-start-enable-service
